### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by alessandro1997** [alessandro1997/the-codeless-code#260]
When I created this repository, I used the MIT license (under my name) because I used it to store my translations only.

Now, the repo contains contributions from 11 people, including the original work of Qi.

What license shall we use?

/cc @QilessQi @galcalde @abelards @cdlm @AdamStelmaszczyk @tsluyter @zhouji2013 @krzysztof-sikorski @c3r @lbarasti

Sorry for pinging you all, but I think we should decide this together.

**Comment by abelards** [comment]
MIT is fine with me, I use it for code.
For content I more often use CC-BY-SA but it's out of habit.
Anyway relicensing might be/become tricky.
I'll stand by whatever you all will choose.

**Comment by alessandro1997** [comment]
Okay, [CC-BY-SA](http://creativecommons.org/licenses/by-sa/4.0/legalcode) is one option. We'll wait for feedback from the others.

**Comment by galcalde** [comment]
I'm on for CC-BY-SA

**Comment by tsluyter** [comment]
Like Sylvain I usually fall back on CC BY SA.

**Comment by AdamStelmaszczyk** [comment]
[CC-BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/) is fine by me.

I think it's good to point out, that if all the text will go under that license, then "remix, transform, and build upon the material for any purpose, even commercially" is legal.

Which means that anyone could make for example a Codeless Code book and sell it for their profit.

I think Qi is the one to make the decision. I'll stand by whatever he choose :)

**Comment by abelards** [comment]
I think the MIT and most OSS licences also allows selling fo profit [1].
But CC-BY and MIT require attribution (the authors be named).
CC-NC would forbid commercial use.

[1] Most OSS do, provided you give the source, which is why you can sell DVDs with Linux or Firefox.
The good thing is: if you shoulder the cost of burning the DVD, you can sell it to make up for the cost.

**Comment by cdlm** [comment]
I'm fine with both MIT and CC-BY-SA (with a preference for the latter one maybe)

**Comment by tsluyter** [comment]
Also: my apologies for not having added anything new for months now :( 

I do intend to continue work on the NL translations sometime soon.

Cheers!


Thomas

**Comment by QilessQi** [comment]
I'm not sure how this has bearing on it, but the original works themselves
are under the Creative Commons Attribution-NonCommercial 3.0 Unported
License:

http://creativecommons.org/licenses/by-nc/3.0/

**Comment by QilessQi** [comment]
I want to make certain that the translators have the ability to do anything with their own work that they like, including selling it.  Even though the original English works are (and continue to be) CC-BY-NC 3.0, I'm okay if the non-English translations are used commercially *by their original translators*.  I am somewhat hesitant of opening up the license in any way that would unintentionally give someone else the ability to profit off a translator's work without their consent.

I suppose I could add a "License:" header to each of the "en-qi" files that re-iterates the CC-BY-NC 3.0 license.  Then the *repository-wide* license could specify whatever the translator community agrees to, "except where otherwise noted in individual files".  What do folks think of that?

**Comment by QilessQi** [comment]
I want to make certain that the translators have the ability to do anything
with their own work that they like, including selling it.  Even though the
original English works are (and continue to be) CC-BY-NC 3.0, I'm okay if
the non-English translations are used commercially *by their original
translators*.  I am somewhat hesitant of opening up the license in any way
that would unintentionally give someone else the ability to profit off a
translator's work without their consent.

I suppose I could add a "License:" header to each of the "en-qi" files that
re-iterates the CC-BY-NC 3.0 license.  Then the *repository-wide* license
could specify whatever the translator community agrees to, "except where
otherwise noted in individual files".  What do folks think of that?

**Comment by krzysztof-sikorski** [comment]
I'm fine with any license - I did not translate for fame nor profit, and I don't even care if and how I am credited or if I am credited at all :)

If I do have to choose, I would prefer the same license as the original work, to keep it consistent.

**Comment by c3r** [comment]
I'm there with @krzysztof-sikorski. I'd rather use same licensing as the original text to keep things consistent.

**Comment by alessandro1997** [comment]
What about allowing every translator to submit their own license via a PR?

**Comment by cdlm** [comment]
@alessandro1997 it's just asking for headaches, IMHO.

**Comment by QilessQi** [comment]
Since the Git repository is Alessandro's baby, I will happily defer to his
judgment.  :-)   To prevent confusion (and possible violations of the
original license) I will stamp a "License:" header on all the original
English text files to clearly separate them from the remainder of the
repository.  That should be sufficient to allow the translators to choose a
licensing scheme which best suits them, including one which allows
commercial use of their work.

Many regards,

Qi

**Comment by abelards** [comment]
I fear some masters would strike me with their staff if I repeat myself with the "License:" tag on each file.
I suggest adding a default license per "author" (translator), in the format you'd like.
Cf https://github.com/alessandro1997/the-codeless-code/pull/267
Cheers!

**Comment by QilessQi** [comment]
Heh... I guess I'm just too accustomed to the paranoia of the American
corporate system: we stamp the same license at the top of every single
source code file, even in closed-source projects.  :-)

Regards,

Qi

**Comment by alessandro1997** [comment]
@cdlm, how so?

@abelards has already submitted a PR (#267).

@QilessQi perhaps you could display the active translator's license next to your own?

**Comment by cdlm** [comment]
@alessandro1997 do you really want to have to check for each file, what license it has?

My stance is, simple is better; therefore, at the moment someones contributes to a project, they (have to) accept that their contribution will take the same license as everything else in the project.

**Comment by alessandro1997** [comment]
If we decide to use the same license for all the translations and that license is different from the original work's, then I can also tolerate that each translator has their own license.

Or, we can use [CC-BY-NC 3.0](http://creativecommons.org/licenses/by-nc/3.0/) and require that all translations are released under that license.

**Comment by QilessQi** [comment]
@QilessQi <https://github.com/QilessQi> perhaps you could display the
active translator's license next to your own?

Certainly; very happy to implement this if that's the direction chosen.


Regards,

Qi

**Comment by cdlm** [comment]
> Or, we can use CC-BY-NC 3.0 and require that all translations are released under that license.

Yes. I won't complain if another solution is selected, this is just one that seems simple & clear while involving a minimum of bureaucracy. What's the point, as a translator, to pick a different license?

**Comment by krzysztof-sikorski** [comment]
> What's the point, as a translator, to pick a different license?
As @QilessQi mentioned, theoretically a translator might want to use his/her work commercially * - the original CC-BY-NC forbids that.

* It's not that hard to imagine, I think even publishing a paperback edition is formally a "commercial activity" even if the price is low and set just to cover the printing fees.

**Comment by alessandro1997** [comment]
^^^

**Comment by alessandro1997** [comment]
Okay, I think we'll go with translator-specific licenses.

Everyone should submit a PR in the fashion of #267 indicating which license they would like to use.
